name: build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  java-build:
    uses: EcommerceDevops/workflows/.github/workflows/build-push-java.yml@main
    with:
      IMAGE_NAME: service-discovery-ecommerce-boot
      JAVA: true
      PROJECT_VERSION: 1.0.0
    secrets: inherit
